[package]
name = "verilog_synthesis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
same-file = "1"
regex = "1"
string-builder = "0.2.0"
chrono = "0.4.23"
